# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code

    # Basic code quality linters
    - gofmt         # Check formatting
    - misspell      # Check for misspelled words

  disable:
    - typecheck     # Disable in favor of build verification

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    enable:
      - shadow

  gofmt:
    simplify: true

  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - errcheck
        - unparam

    # Exclude legacy code patterns
    - path: agent/
      linters:
        - stylecheck

    # Exclude generated code
    - path: (^|/)vendor/
      linters:
        - all

  exclude-use-default: false
